### ISSUE TITLE
[Http.fs bug] error with uploading request body

### ISSUE THREAD

**Issue by saneman1** [fsharp/FSharp.Data#1082] opened 2017-10-08 12:25 UTC
I do PUT http request with some  body, size about 1MB.
The server immediately responds with error status code (409 Conflict), I see it in the traces. After upload of the request body is complete, an error occurs:

WebException: The underlying connection was closed: An unexpected error occurred on a receive.
  IOException: Unable to read data from the transport connection

exception raised at function [getResponseFromBeginEnd](https://github.com/fsharp/FSharp.Data/blob/master/src/Net/Http.fs#L1311)

When size of payload request body less 1MB all ok. 
The cause of the problem the following - by the end of the uploading body server already closes the connection.

How can I work around this issue and retrieve the actual response from the server?

thx, for the library, very usefull !

**Comment by ovatsus** [comment] 2017-10-08 14:37
Can you try to get a code snippet that reproduces the problem?
/cc @baronfel

**Comment by baronfel** [comment] 2017-10-08 14:42
It'll be at least 5 hours until I can look at this (traveling and whatnot) but I definitely will when I get back to my computer.

**Comment by saneman1** [comment] 2017-10-08 14:57
code snippet

    open FSharp.Data
    open System.IO

    let test () = 
        let resp = Http.Request(
                    "https://somewebdav-server/dir1/file1", //server name for example
                    httpMethod = "PUT",
                    headers = [ 
                        HttpRequestHeaders.ContentType "application/binary"
                        HttpRequestHeaders.BasicAuth "user" "pass"
                    ],
                    silentHttpErrors = true,
                    body = BinaryUpload (File.ReadAllBytes("c:\\tmp\sample.zip"))
                  )
        match resp.StatusCode with
        | 201 -> "ok" //all ok
        
       // In my case, I expect this response (and server response this), but exception raised
        | 409 -> "parent directory absent"  // no direcory

**Comment by ovatsus** [comment] 2017-10-08 15:08
Hey Chet, I didn't mean to put any kind of pressure on you, look at this whenever it's convenient, remember this is open source not work :)

**Comment by baronfel** [comment] 2017-10-08 15:23
@ovastus no worries, it's all internal pressure. I feel a tiny sense of ownership/responsibility for breaking it in the first place :)

**Comment by ovatsus** [comment] 2017-10-08 15:29
This one doesn't seem related to your change, probably was already broken.
@saneman1 , did this work in 2.3.3 and got broken on 2.4.0/2.41, or does it fail on both?

**Comment by saneman1** [comment] 2017-10-08 16:14
@ovatsus , I try only in latests version, but suppose this don't work in all.
Becouse problem in HttpWebRequest / HttpWebResponse.
I can found post about a similar [problem](https://stackoverflow.com/questions/26891077/how-to-get-the-http-response-when-the-request-stream-was-closed-during-transfer)

**Comment by saneman1** [comment] 2017-10-08 16:26
Idealy, should cancel transmit request body (if server already send response), but I can't found a way to do it.

**Comment by ovatsus** [comment] 2018-04-10 16:06
Closing since the problem is in HttpWebRequest / HttpWebResponse so there's nothing we can do

**Closed by ovatsus** 2018-04-10 16:06 UTC
Labels: type-bug

**Comment by baronfel** [comment] 2018-04-10 16:08
Potential workaround: switch our internal implementation to use HttpClient from nuget, and add a `paket.dependencies` file declaring that to the folder colocated with `Http.fs`. Then, people who paket-include `Http.fs` will pick up that dependency automatically, per the docs: https://fsprojects.github.io/Paket/github-dependencies.html#Remote-dependencies

**Comment by ovatsus** [comment] 2018-04-10 16:24
I've been trying to avoid adding the dependency to that nuget package. Http.fs is supposed to be a lightweight thing mainly for FSI use, if people have more complex needs they should use libraries like https://github.com/haf/Http.fs instead
