### ISSUE TITLE
Strange Behaviour of Option<bool> in combination of UnitTest-Runner and separate AppDomains 

### ISSUE THREAD

**Issue by 0x53A** [fsharp/FSharp.Data#887] opened 2015-10-30 21:03 UTC
I uploaded the project to https://onedrive.live.com/redir?resid=5062EFE7E0C8ECCC!131311&authkey=!ADVebaLmSKK2Rfg&ithint=file%2czip
To reproduce, you can run the script "Run.fsx". For me, this leads to one successfull and one failing unit test.

  
  
I use the RTM Version of VS2015 Pro, the project targets .Net 4.5.2 and F#3.1 with FSharp.Core 4.3.1.0

I use FSharp.Data 2.2.5

A unit-test fails with 

``Assert.IsTrue failed. "Some true|<null>" = "Some(True)|<null>"``

But it only fails in the UnitTest runner! If I run the same unit test in the Main of the Exe, it succeeds.

If I instead retarget the project to F# 4.0, the unit test succeeds.  

Basically, the unit test reads a value from the XmlProvider, then reads the same value in another AppDomain and compares both.

    module XXX

    open Microsoft.VisualStudio.TestTools.UnitTesting
    open System

    type sampleXmlType = FSharp.Data.XmlProvider< Sample= """<?xml version="1.0" standalone="yes"?>
    <A>
        <G>
            <X>true</X>
        </G>
        <G>

        </G>
    </A>
    """ >

    let get_val =
        let fromSample = sampleXmlType.GetSample().Gs
        fromSample |> Seq.map (fun s -> s.X |> sprintf "%A" ) |> String.concat "|"
    
    type TestRunner() =
        inherit MarshalByRefObject()
        member __.compare (expected) =
            let read = get_val
            Assert.IsTrue((expected = read), sprintf "%A = %A" expected read)

    // If i use the VS-TestExplorer to run the unittests...  
    [<TestClass>]
    type FSharpTests() =

        // this one fails
        [<TestMethod>]
        member __.runTestInAppDomain() =
            let ad = AppDomain.CreateDomain("ad2", null, AppDomainSetup(ApplicationBase = AppDomain.CurrentDomain.SetupInformation.ApplicationBase))
            let t = typeof<TestRunner>
            let tr = ad.CreateInstanceAndUnwrap(t.Assembly.GetName().Name, t.FullName) :?> TestRunner
            tr.compare get_val
    
        // this one is successfull
        [<TestMethod>]
        member __.runTest() =
            let tr = TestRunner()
            tr.compare get_val

    // If i run the EXE with F5, it works        
    [<EntryPoint>]
    let main argv =
        let testClass = FSharpTests()
        testClass.runTest()
        testClass.runTestInAppDomain()
        0

(I tried to reduce it as much as possible, in the original code I had >1k LOC, and at the end I had a collection with 250 elements in the original AppDomain and a collection with 50 elements in the other AppDomain. Figuring out where it was going wrong was fun ...)

**Comment by ovatsus** [comment] 2015-12-21 10:51
Can you try this with 2.3 beta? The new type loader code from @dsyme might have fixed this

**Comment by 0x53A** [comment] 2015-12-30 17:38
Updating the nuget changed nothing, BUT:

Without even updating the nuget, running it in VS 2015.1 now fails early with an exception:

Test Name:	runTestInAppDomain
Test FullName:	XXX+FSharpTests.runTestInAppDomain
Test Source:	C:\Users\lr\Downloads\AppDomainTest\AppDomainTest\Program.fs : line 34
Test Outcome:	Failed
Test Duration:	0:00:01.4045367

Result StackTrace:	
at FSharp.Data.Runtime.XmlRuntime.GetChildrenArray(XmlElement value, String nameWithNS)
   at FSharp.Data.Runtime.XmlRuntime.ConvertArray[R](XmlElement xml, String nameWithNS, Func`2 f) in C:\Git\FSharp.Data\src\Xml\XmlRuntime.fs:line 158
   at <StartupCode$AppDomainTest>.$XXX..cctor() in C:\Users\lr\Downloads\AppDomainTest\AppDomainTest\Program.fs:line 18
 --- End of inner exception stack trace ---
    at XXX.get_get_val()
   at XXX.TestRunner.compare(String expected) in C:\Users\lr\Downloads\AppDomainTest\AppDomainTest\Program.fs:line 24
   at XXX.TestRunner.compare(String expected)
   at XXX.FSharpTests.runTestInAppDomain() in C:\Users\lr\Downloads\AppDomainTest\AppDomainTest\Program.fs:line 37
Result Message:	
Test method XXX+FSharpTests.runTestInAppDomain threw exception: 
System.TypeInitializationException: The type initializer for '<StartupCode$AppDomainTest>.$XXX' threw an exception. ---> System.IO.FileLoadException: Could not load file or assembly 'FSharp.Core, Version=4.3.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)


Also, the behaviour for F#4 changed:

| FS | Result |
|-----|----------|
|3.0 (FSharp.Core 4.3.0.0) | OK |
|3.1 (FSharp.Core 4.3.1.0) | TypeInitializationException|
|4.0 (FSharp.Core 4.4.0.0) | TypeInitializationException|

So this is probably not related to FSharp.Data but a bug in the VS TestRunner and how it sets up the AppDomains for the unit tests.

This issue is not really relevant for us any more, I have been able to work around it by reading the data in the original app-domain and then just passing it through, and am currently working on removing the AppDomain dance altogether.

**Comment by ovatsus** [comment] 2016-05-01 16:21
Closing as the issue is not with F# Data itself

**Closed by ovatsus** 2016-05-01 16:21 UTC
