### ISSUE TITLE
CSV Type Provider doesn't process lines after an error line

### ISSUE THREAD

**Issue by misterspeedy** [fsharp/FSharp.Data#824] opened 2015-05-08 07:40 UTC
When the CSV Type Provider (with IgnoreErrors turned on) encounters a line containing, for example, an odd number of double-quotes, it only produces data for the preceding lines.  Any following lines which are valid are not returned.

**Comment by ovatsus** [comment] 2015-05-08 10:17
That's odd, can you share a small sample repro, maybe submit a PR with a failing test?

**Comment by drcrook1** [comment] 2015-05-11 12:49
I've got the same issue.  I'm dealing with the Zillow data...
    [<Literal>]
    let zillowBasicSample = "http://www.zillow.com/webservice/GetUpdatedPropertyDetails.htm?zws-id=YOURKEY&zpid=48749425"
    let zillowBasicUrl = "http://www.zillow.com/webservice/GetUpdatedPropertyDetails.htm?zws-id=YOURKEY&zpid="
    [<Literal>]
    let zillowDeepSample = "http://www.zillow.com/webservice/GetDeepSearchResults.htm?zws-id=YOURKEY&address=2114+Bigelow+Ave&citystatezip=Seattle%2C+WA"
    let zillowDeepsUrl = "http://www.zillow.com/webservice/GetDeepSearchResults.htm?zws-id=YOURKEY"
    type ZillowBasic = XmlProvider<zillowBasicSample>
    type ZillowDeep = XmlProvider<zillowDeepSample>

    let GetHome (id:int) = 
        let idString = id.ToString()
        let zBasic = ZillowBasic.Load(zillowBasicUrl + idString)
        let address = zBasic.Response.Address.Street.Replace(" ", "+")
        let citystatezip = zBasic.Response.Address.City + @"%2C+" + zBasic.Response.Address.State
        let deepUrl = zillowDeepsUrl + "&address=" + address + "citystatezip=" + citystatezip
        let zFull = ZillowDeep.Load(zillowDeepsUrl + "&address=" + address + "&citystatezip=" + citystatezip)
        let home = new Home();
       home.LastSoldDate <- zFull.Response.Result.LastSoldDate

My requested method of handling this is to return me either nullables or option types.

**Comment by drcrook1** [comment] 2015-05-11 12:49
My issue is with the XML Provider.

**Comment by tpetricek** [comment] 2015-06-07 18:24
The original issue might be that if you have invalid line with an odd number of quotes, it actually treats the rest of the file as a single value. E.g.

    Foo, Bar
    1, "hi, there"
    2, "hi, there
    3, stuff

This is broken CSV, but it is broken in a very subtle way (and we cannot really automatically fix this). The XML provider issue seems to be unrelated, but we need a small reproducible sample.

**Comment by ovatsus** [comment] 2015-06-07 18:27
In any case, even if line 2 is invalid, shouldn't we still process 3 and subsequent lines?

**Comment by tpetricek** [comment] 2015-06-07 21:20
Well, it is hard to decide what the right thing to do is - because quoted strings in CSV can be multi-line. So the following (just added quote to the end and one more line) is valid CSV...

    Foo, Bar
    1, "hi, there"
    2, "hi, there
    3, stuff"
    4, "hi there"

... which has 3 rows (where the second one contains "hi, there\n3, stuff" as the last column value.

**Comment by ovatsus** [comment] 2015-10-11 16:54
Closing as by design

**Closed by ovatsus** 2015-10-11 16:54 UTC
Labels: type-bug, up-for-grabs
