### ISSUE TITLE
JsonValue has two numeric data types whilst JSON only has one.

### ISSUE THREAD

**Issue by endeavour** [fsharp/FSharp.Data#1164] opened 2018-05-15 10:21 UTC
Javascript/JSON only has one numeric data type so this feels like the domain has been modelled wrong and makes pattern matching after parsing more complicated than it needs to be: if I parse JSON document and want to extract a numeric value via a pattern match, how do I know if I'm going to get a JsonValue.Number (decimal) or a JsonValue.Float?

Since javascript represents numbers as doubles, I would suggest just getting rid of JsonValue.Number altogether. Thoughts?

**Comment by ovatsus** [comment] 2018-07-08 21:39
This was intentional to keep with the spirit of F# and try to be safer. JSON these days is used in a lot of places not directly tied to JavaScript so it didn't seem that matching JavaScript was important. So numbers are parsed to decimal by default, and only when not possible they are parsed as float. That does means that we have to pattern match on both, but we think it's worth it.
Closing as by design

**Closed by ovatsus** 2018-07-08 21:39 UTC
