### ISSUE TITLE
Reference order issue for library which depends on FSharp.Data 

### ISSUE THREAD

**Issue by v-zubritsky** [fsharp/FSharp.Data#899] opened 2015-12-21 09:41 UTC
Got dlls reference order issue, while consuming library, which depend on `FSharp.Data`, from `fsx` scipt in interactive mode.

I have a library, which depends on `FSharp.Data` and exports `JsonProvider` generated type from its api. Then, while trying to use that library from interactive script, I get error `FS0074: The type referenced through 'FSharp.Data.JsonProvider,Sample="{\"reference\": \"FSharp.Data\"}".Root' is defined in an assembly that is not referenced. You must add a reference to assembly 'FSharp.Data'.` if `FSharp.Data` is referenced after library in my script. But everything works fine, if `FSharp.Data` is referenced before the library.

So, I'm expecting that at the time of library direct usage all the dlls are loaded and it's not important in which order, but expectation fails.

Small solution to reproduce [asm-order.zip](https://github.com/fsharp/FSharp.Data/files/68297/asm-order.zip).

`asm-order` - library, which depends on `FSharp.Data`
`Test.fsx` - script to test unexpected behavior.

Fails if `Test.fsx` loads assemblies in this order:

    #I __SOURCE_DIRECTORY__
    #r @"asm-order\bin\Debug\asm_order.dll"
    #r "lib\FSharp.Data.dll"

And works fine at this case:
    
    #I __SOURCE_DIRECTORY__
    #r "lib\FSharp.Data.dll"
    #r @"asm-order\bin\Debug\asm_order.dll"

**Comment by ovatsus** [comment] 2015-12-21 10:44
I think this might be by design with assemblies with erased TPs
/cc @dsyme

**Comment by tpetricek** [comment] 2015-12-29 23:59
The F# Data Toolbox Twitter has the same issue. That's why it comes with a huge warning box: http://fsprojects.github.io/FSharp.Data.Toolbox/TwitterProvider.html

I think it is sort-of-by-design, but it would be nice to see this fixed.

**Comment by dsyme** [comment] 2016-02-09 18:11
This should be considered a bug in F#, please add to http://github.com/Microsoft/visualfsharp.  We may need another phase of assembly loading....

**Comment by tpetricek** [comment] 2016-04-25 16:56
Closing this issue here.

**Closed by tpetricek** 2016-04-25 16:56 UTC
