### ISSUE TITLE
JsonProvider HTTP Headers

### ISSUE THREAD

**Issue by ijoyce** [fsharp/FSharp.Data#893] opened 2015-11-29 23:17 UTC
I often need to pass in custom http headers to restful endpoints that return JSON. Such as:
```Javascript
X-API-Key: MySecreyKey
Content-Type: application/hal+json
```

I was thinking something along the lines of
```fsharp
#r "FSharp.Data.dll"

[<Literal>]
let sample = "http://api.openweathermap.org/data/2.5/weather?q=London"
let apiUrl = "http://api.openweathermap.org/data/2.5/weather?q="
let headers = ["X-API-Key"; "MySecretKey"; "Content-Type"; "application/hal+json"]

type Weather = JsonProvider<sample, Headers=headers>

let sf = Weather.Load(apiUrl + "San Francisco", headers)
sf.Sys.Country
sf.Wind.Speed
sf.Main.Temp
```

Thoughts? Maybe this is already doable, but if not I'd be willing to submit a PR.

**Comment by ovatsus** [comment] 2015-11-30 11:56
You can use Http.RequestString to get the file, which supports all of that, and then feed it to JsonProvider

**Comment by ovatsus** [comment] 2015-12-21 10:48
The sample can either be a url or a file, so it would be a bit weird to support headers directly as a TP static param. Given that's so easy to just get the file first, I'm closing this a by design

**Closed by ovatsus** 2015-12-21 10:48 UTC
