### ISSUE TITLE
"This stream does not support writing" on mono 5.0.0.48 for Http.RequestString

### ISSUE THREAD

**Issue by mastoj** [fsharp/FSharp.Data#1053] opened 2017-05-11 20:42 UTC
I'm trying to use the http utilities but get a weird error I haven't seen before.

```
System.InvalidOperationException: This stream does not support writing
  at System.IO.Compression.DeflateStream.BeginWrite (System.Byte[] buffer, System.Int32 offset, System.Int32 count, Syst
em.AsyncCallback cback, System.Object state) [0x00021] in <ee4df4cda5014c96916f8e16adf2d907>:0
  at System.IO.Stream+<>c.<BeginEndWriteAsync>b__53_0 (System.IO.Stream stream, System.IO.Stream+ReadWriteParameters arg
s, System.AsyncCallback callback, System.Object state) [0x00000] in <164469fa6d844a078126fd8006807335>:0
  at System.Threading.Tasks.TaskFactory`1[TResult].FromAsyncTrim[TInstance,TArgs] (TInstance thisRef, TArgs args, System
.Func`5[T1,T2,T3,T4,TResult] beginMethod, System.Func`3[T1,T2,TResult] endMethod) [0x00008] in <164469fa6d844a078126fd80
06807335>:0
  at System.IO.Stream.BeginEndWriteAsync (System.Byte[] buffer, System.Int32 offset, System.Int32 count) [0x00000] in <1
64469fa6d844a078126fd8006807335>:0
  at System.IO.Stream.WriteAsync (System.Byte[] buffer, System.Int32 offset, System.Int32 count, System.Threading.Cancel
lationToken cancellationToken) [0x00009] in <164469fa6d844a078126fd8006807335>:0
  at System.IO.Compression.GZipStream.WriteAsync (System.Byte[] array, System.Int32 offset, System.Int32 count, System.T
hreading.CancellationToken cancellationToken) [0x00006] in <ee4df4cda5014c96916f8e16adf2d907>:0
  at System.IO.Compression.GZipStream.BeginRead (System.Byte[] array, System.Int32 offset, System.Int32 count, System.As
yncCallback asyncCallback, System.Object asyncState) [0x00009] in <ee4df4cda5014c96916f8e16adf2d907>:0
  at Microsoft.FSharp.Control.CommonExtensions+AsyncRead@2132.Invoke (System.Tuple`5[T1,T2,T3,T4,T5] tupledArg) [0x00025
] in <58e7b19fdff9fae1a74503839fb1e758>:0
  at <StartupCode$FSharp-Core>.$Control+FromBeginEnd@1895-4[TArg1,TArg2,TArg3].Invoke (System.Tuple`2[T1,T2] tupledArg)
[0x0002e] in <58e7b19fdff9fae1a74503839fb1e758>:0
  at <StartupCode$FSharp-Core>.$Control+FromBeginEnd@1834-1[T].Invoke (System.Threading.CancellationToken _arg4) [0x0005
c] in <58e7b19fdff9fae1a74503839fb1e758>:0
  at Microsoft.FSharp.Control.AsyncBuilderImpl+args@823-1[a,b].Invoke (a a) [0x00016] in <58e7b19fdff9fae1a74503839fb1e7
58>:0
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <164469fa6d844a078126fd8006807335>:0
  at Microsoft.FSharp.Control.AsyncBuilderImpl.commit[a] (Microsoft.FSharp.Control.AsyncBuilderImpl+AsyncImplResult`1[T]
 res) [0x0002d] in <58e7b19fdff9fae1a74503839fb1e758>:0
  at Microsoft.FSharp.Control.CancellationTokenOps.RunSynchronouslyInCurrentThread[a] (System.Threading.CancellationToke
n token, Microsoft.FSharp.Control.FSharpAsync`1[T] computation) [0x00029] in <58e7b19fdff9fae1a74503839fb1e758>:0
  at Microsoft.FSharp.Control.CancellationTokenOps.RunSynchronously[a] (System.Threading.CancellationToken token, Micros
oft.FSharp.Control.FSharpAsync`1[T] computation, Microsoft.FSharp.Core.FSharpOption`1[T] timeout) [0x00014] in <58e7b19f
dff9fae1a74503839fb1e758>:0
  at Microsoft.FSharp.Control.FSharpAsync.RunSynchronously[T] (Microsoft.FSharp.Control.FSharpAsync`1[T] computation, Mi
crosoft.FSharp.Core.FSharpOption`1[T] timeout, Microsoft.FSharp.Core.FSharpOption`1[T] cancellationToken) [0x00071] in <
58e7b19fdff9fae1a74503839fb1e758>:0
  at FSharp.Data.Http.RequestString (System.String url, Microsoft.FSharp.Core.FSharpOption`1[T] query, Microsoft.FSharp.
Core.FSharpOption`1[T] headers, Microsoft.FSharp.Core.FSharpOption`1[T] httpMethod, Microsoft.FSharp.Core.FSharpOption`1
[T] body, Microsoft.FSharp.Core.FSharpOption`1[T] cookies, Microsoft.FSharp.Core.FSharpOption`1[T] cookieContainer, Micr
osoft.FSharp.Core.FSharpOption`1[T] silentHttpErrors, Microsoft.FSharp.Core.FSharpOption`1[T] responseEncodingOverride,
Microsoft.FSharp.Core.FSharpOption`1[T] customizeHttpRequest, Microsoft.FSharp.Core.FSharpOption`1[T] timeout) [0x00019]
 in <57950ff10a968414a7450383f10f9557>:0
  at <StartupCode$FSI_0002>.$FSI_0002.main@ () [0x0005c] in <b3e6a19481014d0c9b3acd5495987309>:0
  at (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (System.Reflection.MonoMethod,object,object
[],System.Exception&)
  at System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflectio
n.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00032] in <164469fa6d844a07812
6fd8006807335>:0
Stopped due to error
```

I'm not sure this is because I updated to mono 5.0.0, could be. Downgraded to latest stable, 4.8.1, and it worked.

The code I'm running is really simple: 

    let response = Http.RequestString("https://www.twitter.com")

**Comment by mastoj** [comment] 2017-05-12 06:20
I've registered an issue on mono: https://bugzilla.xamarin.com/show_bug.cgi?id=56260

**Comment by dsyme** [comment] 2017-05-12 12:25
@mastoj @tpetricek We should probably find a workaround for this rather than waiting for a Mono fix?

**Comment by sergey-tihon** [comment] 2017-05-12 13:55
Duplicate of #1052

**Comment by mastoj** [comment] 2017-05-12 16:30
@dsyme should it still be fixed when a mono fix is already there : https://bugzilla.xamarin.com/show_bug.cgi?id=56260, but not released in any 5.0.x release yet. I think the fix is available in beta 5.2.x releases. However, people downloading the stable release will have issues.

**Comment by dsyme** [comment] 2017-05-12 16:39
I see.  I guess waiting is ok

**Comment by mastoj** [comment] 2017-05-12 17:33
A fix will be out asap: https://mobile.twitter.com/migueldeicaza/status/863078651985666048

**Comment by nosami** [comment] 2017-05-17 09:55
Fixed in CoreFX https://github.com/dotnet/corefx/commit/a6c7e23421701870c1eb855eae95e4605e5b04b3

**Comment by sergey-tihon** [comment] 2017-05-25 19:53
Should be fixed in released Mono 5.0.1

**Comment by realvictorprm** [comment] 2017-09-14 21:40
@tpetricek I think this can be closed.

**Comment by tpetricek** [comment] 2017-09-14 23:45
Thanks!

**Closed by tpetricek** 2017-09-14 23:45 UTC
